# Generated by Django 3.1.1 on 2021-11-02 15:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20211024_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='age',
        ),
        migrations.AddField(
            model_name='agent',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='agent',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lead',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='lead',
            name='discription',
            field=models.TextField(default='None'),
        ),
    ]
