# Generated by Django 3.1.1 on 2021-11-02 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20211102_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
