# Generated by Django 3.1.1 on 2021-11-02 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20211102_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
