# Generated by Django 3.1.1 on 2021-11-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20211102_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.userprofile'),
        ),
    ]
